lib/pintxos_web/router.ex
defmodule PintxosWeb.Router do
  use PintxosWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :auth_browser do
    plug :browser
    plug PintxosWeb.Plugs.AuthenticateSession, protected: true
  end

  pipeline :admin_auth_browser do
    plug :browser
    plug PintxosWeb.Plugs.AdminAuthenticateSession, protected: true
  end


  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PintxosWeb do
    pipe_through :browser

    resources "/sessions", SessionController, only: [:new, :create]
  end

  scope "/", PintxosWeb do
    pipe_through :auth_browser

    get "/", PageController, :index

    delete "/sign_out", SessionController, :delete

    resources "/pintxos", PintxoController #, only: [:new, :create, :show]
  end

  scope "/", PintxosWeb do
    pipe_through :admin_auth_browser

    resources "/contests", ContestController
    put "/contests/activate/:id", ContestController, :activate
  end

  # Other scopes may use custom stacks.
  # scope "/api", PintxosWeb do
  #   pipe_through :api
  # end
end

lib/pintxos_web/views/layout_view.ex
defmodule PintxosWeb.LayoutView do
  use PintxosWeb, :view
end

lib/pintxos_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Pintxos</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <%= if Pintxos.Auth.user_signed_in?(@conn) do %>
            <nav class="my-2 my-md-0 mr-md-3">
              <strong><%= Pintxos.Auth.current_user(@conn).username %></strong>
              <%= if Pintxos.Auth.user_is_admin?(@conn) do %>(Admin)<% end %>
            </nav>
            <%= link gettext("Sign Out"), to: Routes.session_path(@conn, :delete), method: :delete, class: "btn btn-outline-primary" %>
          <% else %>
            <%= link gettext("Sign In"), to: Routes.session_path(@conn, :new), class: "btn btn-outline-primary" %>
          <% end %>
        </nav>
        <img src="<%= Routes.static_path(@conn, "/images/pintxos.png") %>" alt="Phoenix Framework Logo" height="150"/>
      </section>
    </header>
    <main role="main" class="container">
      <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
        
      </div>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>